# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIs\QR_Generator_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 340)
        MainWindow.setMinimumSize(QtCore.QSize(310, 340))
        MainWindow.setMaximumSize(QtCore.QSize(310, 340))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plain_text_edit_convert_to_qr = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_text_edit_convert_to_qr.setGeometry(QtCore.QRect(10, 30, 291, 271))
        self.plain_text_edit_convert_to_qr.setObjectName("plain_text_edit_convert_to_qr")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 291, 16))
        self.label.setObjectName("label")
        self.btn_qr_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_qr_generate.setGeometry(QtCore.QRect(10, 310, 291, 23))
        self.btn_qr_generate.setObjectName("btn_qr_generate")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Text For convert to QR"))
        self.btn_qr_generate.setText(_translate("MainWindow", "QR Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
