# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIs\Show_QR_Generated_By_Your_Text_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 600)
        MainWindow.setMinimumSize(QtCore.QSize(520, 600))
        MainWindow.setMaximumSize(QtCore.QSize(520, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 502, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(500, 0))
        self.label.setMaximumSize(QtCore.QSize(500, 20))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_show_image_qr = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_show_image_qr.setMinimumSize(QtCore.QSize(3, 0))
        self.label_show_image_qr.setMaximumSize(QtCore.QSize(500, 500))
        self.label_show_image_qr.setStyleSheet("")
        self.label_show_image_qr.setText("")
        self.label_show_image_qr.setScaledContents(True)
        self.label_show_image_qr.setObjectName("label_show_image_qr")
        self.verticalLayout.addWidget(self.label_show_image_qr)
        self.btn_show_file_dialog_save_file_url = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_show_file_dialog_save_file_url.setObjectName("btn_show_file_dialog_save_file_url")
        self.verticalLayout.addWidget(self.btn_show_file_dialog_save_file_url)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Qr Generated By Your Text"))
        self.btn_show_file_dialog_save_file_url.setText(_translate("MainWindow", "Save As..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
